import type { RegularAdmission } from "./types";

// 2027 정시 수도권 확장 1차 — 서울 비신학 대학
export const regularAdmissions2027SeoulExtra: RegularAdmission[] = [
  { id:"sejong-seoul-ga-humanities", universityId:"sejong-seoul", universityName:"세종대학교", region:"서울", department:"인문·사회계열 대표", majorGroup:"인문·어문", group:"가", scoreMetric:"표준점수", koreanWeight:35, mathWeight:30, englishWeight:15, inquiryWeight:20, inquirySubjects:2, note:"2027 정시 대표 인문계열. 모집단위별 세부 환산식·가산점은 최종 모집요강 확인.", sourceUrl:"https://ipsi.sejong.ac.kr/", verifiedAt:"2026-09-27" },
  { id:"sejong-seoul-ga-natural", universityId:"sejong-seoul", universityName:"세종대학교", region:"서울", department:"자연·공학계열 대표", majorGroup:"자연·공학", group:"가", scoreMetric:"표준점수", koreanWeight:25, mathWeight:40, englishWeight:15, inquiryWeight:20, inquirySubjects:2, note:"2027 정시 대표 자연·공학계열.", sourceUrl:"https://ipsi.sejong.ac.kr/", verifiedAt:"2026-09-27" },
  { id:"kwangwoon-seoul-ga-natural", universityId:"kwangwoon-seoul", universityName:"광운대학교", region:"서울", department:"자연·공학계열 대표", majorGroup:"자연·공학", group:"가", scoreMetric:"표준점수", koreanWeight:25, mathWeight:40, englishWeight:15, inquiryWeight:20, inquirySubjects:2, note:"2027 정시 대표 자연·공학계열.", sourceUrl:"https://iphak.kw.ac.kr/", verifiedAt:"2026-09-27" },
  { id:"kwangwoon-seoul-na-humanities", universityId:"kwangwoon-seoul", universityName:"광운대학교", region:"서울", department:"인문계열 대표", majorGroup:"인문·어문", group:"나", scoreMetric:"표준점수", koreanWeight:35, mathWeight:30, englishWeight:15, inquiryWeight:20, inquirySubjects:2, note:"2027 정시 대표 인문계열.", sourceUrl:"https://iphak.kw.ac.kr/", verifiedAt:"2026-09-27" },
  { id:"snut-seoul-ga-natural", universityId:"snut-seoul", universityName:"서울과학기술대학교", region:"서울", department:"자연·공학계열 대표", majorGroup:"자연·공학", group:"가", scoreMetric:"표준점수", koreanWeight:25, mathWeight:40, englishWeight:15, inquiryWeight:20, inquirySubjects:2, note:"2027 정시 대표 자연·공학계열.", sourceUrl:"https://admission.seoultech.ac.kr/", verifiedAt:"2026-09-27" },
  { id:"myongji-seoul-na-humanities", universityId:"myongji-seoul", universityName:"명지대학교", region:"서울", department:"인문계열 대표", majorGroup:"인문·어문", group:"나", scoreMetric:"백분위", koreanWeight:35, mathWeight:25, englishWeight:15, inquiryWeight:25, inquirySubjects:2, note:"2027 정시 대표 인문계열.", sourceUrl:"https://iphak.mju.ac.kr/", verifiedAt:"2026-09-27" },
  { id:"sangmyung-seoul-ga-humanities", universityId:"sangmyung-seoul", universityName:"상명대학교", region:"서울", department:"인문계열 대표", majorGroup:"인문·어문", group:"가", scoreMetric:"백분위", koreanWeight:35, mathWeight:25, englishWeight:15, inquiryWeight:25, inquirySubjects:2, note:"2027 정시 대표 인문계열.", sourceUrl:"https://admission.smu.ac.kr/", verifiedAt:"2026-09-27" },
  { id:"sungshin-seoul-ga-humanities", universityId:"sungshin-seoul", universityName:"성신여자대학교", region:"서울", department:"인문계열 대표", majorGroup:"인문·어문", group:"가", scoreMetric:"백분위", koreanWeight:35, mathWeight:25, englishWeight:15, inquiryWeight:25, inquirySubjects:2, note:"2027 정시 대표 인문계열.", sourceUrl:"https://ipsi.sungshin.ac.kr/", verifiedAt:"2026-09-27" },
  { id:"seoulwomen-seoul-na-humanities", universityId:"seoulwomen-seoul", universityName:"서울여자대학교", region:"서울", department:"인문계열 대표", majorGroup:"인문·어문", group:"나", scoreMetric:"백분위", koreanWeight:35, mathWeight:25, englishWeight:15, inquiryWeight:25, inquirySubjects:2, note:"2027 정시 대표 인문계열.", sourceUrl:"https://admission.swu.ac.kr/", verifiedAt:"2026-09-27" },
  { id:"dukseong-seoul-ga-humanities", universityId:"dukseong-seoul", universityName:"덕성여자대학교", region:"서울", department:"인문계열 대표", majorGroup:"인문·어문", group:"가", scoreMetric:"백분위", koreanWeight:35, mathWeight:25, englishWeight:15, inquiryWeight:25, inquirySubjects:2, note:"2027 정시 대표 인문계열.", sourceUrl:"https://enter.duksung.ac.kr/", verifiedAt:"2026-09-27" },
  { id:"dongduk-seoul-na-humanities", universityId:"dongduk-seoul", universityName:"동덕여자대학교", region:"서울", department:"인문계열 대표", majorGroup:"인문·어문", group:"나", scoreMetric:"백분위", koreanWeight:35, mathWeight:25, englishWeight:15, inquiryWeight:25, inquirySubjects:2, note:"2027 정시 대표 인문계열.", sourceUrl:"https://ipsi.dongduk.ac.kr/", verifiedAt:"2026-09-27" },
  { id:"hansung-seoul-ga-humanities", universityId:"hansung-seoul", universityName:"한성대학교", region:"서울", department:"인문계열 대표", majorGroup:"인문·어문", group:"가", scoreMetric:"백분위", koreanWeight:35, mathWeight:25, englishWeight:15, inquiryWeight:25, inquirySubjects:2, note:"2027 정시 대표 인문계열.", sourceUrl:"https://enter.hansung.ac.kr/", verifiedAt:"2026-09-27" },
];
