import type { RegularAdmission } from "./types";

const HANYANG_SOURCE = "https://go.hanyang.ac.kr/main.do";

// 2027 정시 시행계획/대입정보포털 확인 데이터. 최종 모집요강의 모집단위별 세부값은 순차 보강한다.
export const regularAdmissions2027: RegularAdmission[] = [
  {
    id: "hanyang-seoul-ga-general",
    universityId: "hanyang-seoul",
    universityName: "한양대학교",
    region: "서울",
    department: "인문·자연·상경계열 전체",
    majorGroup: "전체",
    group: "가",
    recruitmentCount: 541,
    scoreMetric: "표준점수",
    koreanWeight: 25,
    mathWeight: 35,
    englishWeight: 10,
    inquiryWeight: 30,
    inquirySubjects: 2,
    note: "일반 495명 + 연극영화(영화) 10명 + 스포츠매니지먼트 17명 + 연출및스탭 6명 + 연기 13명",
    sourceUrl: HANYANG_SOURCE,
    verifiedAt: "2026-09-14",
  },
  {
    id: "hanyang-seoul-na-general",
    universityId: "hanyang-seoul",
    universityName: "한양대학교",
    region: "서울",
    department: "인문·자연·상경계열 전체",
    majorGroup: "전체",
    group: "나",
    recruitmentCount: 619,
    scoreMetric: "표준점수",
    koreanWeight: 25,
    mathWeight: 35,
    englishWeight: 10,
    inquiryWeight: 30,
    inquirySubjects: 2,
    note: "일반 593명 + 반도체공학과 8명 + 스포츠사이언스 18명",
    sourceUrl: HANYANG_SOURCE,
    verifiedAt: "2026-09-14",
  },
  {
    id: "hanyang-seoul-da-intercollege",
    universityId: "hanyang-seoul",
    universityName: "한양대학교",
    region: "서울",
    department: "한양인터칼리지학부",
    majorGroup: "전체",
    group: "다",
    recruitmentCount: 60,
    scoreMetric: "표준점수",
    koreanWeight: 25,
    mathWeight: 35,
    englishWeight: 10,
    inquiryWeight: 30,
    inquirySubjects: 2,
    note: "수능 90% + 학생부종합평가 10%",
    sourceUrl: HANYANG_SOURCE,
    verifiedAt: "2026-09-14",
  },
];
