import type { AdmissionRegion, DataSource } from "./types";
import { admissionSources } from "./sources";

export type CoverageStatus = "확장대기" | "부분검증";
export type CoverageTarget = { universityId: string; name: string; region: AdmissionRegion; status: CoverageStatus; priority: number; source: DataSource; note: string };
const adiga = (url: string): DataSource => ({ type: "adiga", url, academicYear: 2027, confidence: 0.95 });

export const coverageTargets2027: CoverageTarget[] = [
  { universityId: "anyang", name: "안양대학교", region: "경기", status: "부분검증", priority: 1, source: adiga("https://www.adiga.kr/ucp/uvt/uni/univDetail.do?menuId=PCUVTINF2000&searchSyr=2027&unvCd=0000147"), note: "2027 수시 최종 모집요강을 대조해 자유전공·유아교육·글로벌경영·행정·데이터사이언스·AI·디지털미디어디자인·정보전기전자·환경에너지·스포츠 핵심 모집단위의 아리학생부교과·아리학생부면접·아리학생부종합을 verified로 편입. 전체 모집단위와 특수전형·실기전형은 추가 검증한다." },
  { universityId: "sookmyung", name: "숙명여자대학교", region: "서울", status: "부분검증", priority: 1, source: adiga("https://www.adiga.kr/ucp/uvt/uni/univDetailSelection.do?menuId=PCUVTINF2000&searchSyr=2027&unvCd=0000141"), note: "핵심 모집단위·전형을 verified 데이터로 편입. 전체 모집단위/전형별 세부 검증은 계속 진행." },
  { universityId: "seoultech", name: "서울과학기술대학교", region: "서울", status: "부분검증", priority: 1, source: adiga("https://www.adiga.kr/ucp/uvt/uni/univDetailSelection.do?menuId=PCUVTINF2000&searchSyr=2027&unvCd=0000036"), note: "2027 최종 수시 자료와 대교협 심의 후 수정 시행계획을 교차검증해 53개 수시 모집단위 카탈로그, 11개 전형 정의, 전형별 공식 총 모집인원을 반영했다. 모집단위별 숫자는 표 구조상 일부 세부 전형의 열 정렬이 불명확한 경우 임의 재배분하지 않고 전형 합계로 보존한다." },
  { universityId: "sejong", name: "세종대학교", region: "서울", status: "부분검증", priority: 1, source: admissionSources.sejong2027, note: "2027 최종 수시모집요강과 대입정보포털을 교차검증해 수시 전체 1,857명과 전형별 공식 총원을 전형 합계로 보존했다. 면접형 1단계 서류100% 3배수 후 2단계 60+면접40, 서류형 서류100%, 논술 논술80+교과20, 항공시스템공학 교과 1단계 5배수 후 공군전형을 확인했다. 계열선발과 학과선발이 병행되는 전형의 모집단위별 숫자는 임의 재배분하지 않아 부분검증을 유지한다." },
  { universityId: "hongik", name: "홍익대학교", region: "서울", status: "부분검증", priority: 2, source: { type: "university", url: "https://www.hongik.ac.kr/kr/admission/recruitment.do?articleNo=152315", academicYear: 2027, confidence: 0.99 }, note: "홍익대 공식 2027 수시 모집요강(2026-05-29)을 원문으로 대조했다. 서울캠퍼스 37개, 세종캠퍼스 17개 모집단위의 전형별 모집인원을 반영하고, 캠퍼스별 전형 합계(서울 1,783명·세종 974명)도 별도 보존했다. 서울은 학교장추천 307·학교생활우수자 467·고른기회Ⅰ 15·고른기회Ⅱ 10·기초생활 30·농어촌 37·특성화고졸재직자 185·논술 384·미술우수자 289·미술 농어촌 11·공연예술 48, 세종은 교과우수자 315·학교생활우수자 199·고른기회Ⅰ 10·고른기회Ⅱ 6·기초생활 14·농어촌 21·논술 195·미술우수자 182·미술 농어촌 7·체육우수자 25로 확인했다. 2027 수능최저는 서울 학교장추천·학교생활우수자·논술 및 세종 교과우수자·논술에서 2개 영역 합 5로 완화됐으며, 서울 논술은 교과10+논술90, 미술우수자는 1단계 3배수 후 교과20+서류80 및 2단계 40+면접60, 세종 체육우수자는 1단계 8배수 교과80+출결20 후 2단계 30+실기70으로 확인했다. 모집요강의 계열·캠퍼스별 구조를 그대로 반영했으며 임의 숫자 재배분은 하지 않아 부분검증을 유지한다." },
  { universityId: "catholic", name: "가톨릭대학교", region: "경기", status: "부분검증", priority: 2, source: admissionSources.catholic2027, note: "2027 공식 수시 자료를 기준으로 성심교정 핵심 모집단위와 성의교정 의예과·간호학과까지 verified 편입. 현재 자유전공·인문사회·자연공학·바이오·AI의공학·정보통신전자·미디어기술콘텐츠·약학 등은 학과 존재는 확인했으나 2027 전형별 모집인원/반영방법을 공식 원문으로 충분히 대조하지 못해 추천 데이터에는 아직 편입하지 않는다. 논술·특수전형 및 나머지 모집단위는 추가 검증한다." },
  { universityId: "sungkyul", name: "성결대학교", region: "경기", status: "부분검증", priority: 1, source: adiga("https://www.adiga.kr/ucp/uvt/uni/univDetailSelection.do?menuId=PCUVTINF2000&searchSyr=2027&unvCd=0000131"), note: "2027 성결대 공식 입학처에서 신설·명칭변경 모집단위 12개를 확인해 verified 데이터에 편입했다. 한국어문화학과·영미언어문화학과·중국어문화학과·스마트관광항공학부 2개 전공·국제교류·개발협력학과·컴퓨터AI공학과·ICT공학과·산업시스템공학과·스마트도시공학과·화장품공학과·SK자율전공학부가 확인됐다. 다만 최종 모집요강 기준 학과별 모집인원/전형 배정은 별도 대조가 필요하므로 부분검증을 유지한다." },
  { universityId: "hanshin", name: "한신대학교", region: "경기", status: "부분검증", priority: 1, source: adiga("https://www.adiga.kr/ucp/uvt/uni/univDetailSelection.do?menuId=PCUVTINF2000&searchSyr=2027&unvCd=0000202"), note: "2027 최종 수시 모집요강과 대입정보포털 자료를 교차검증했다. 총 1,136명(정원내 1,073·정원외 63)이며 논술 231·참인재 315·학생부우수자 324·학교장추천 55·사회배려자 63·고른기회 63·체육실기 22·기회균형선발 26·농어촌학생 20·특성화고교졸업자 17명을 확인했다. 계열모집 9개·자유전공학부·AI시스템반도체학을 모집단위 카탈로그로 반영하고, 전형방법은 논술80+교과20, 참인재 교과60+면접40, 일반 교과전형 100, 체육실기 교과45+실기55로 반영했다. 모집단위별 세부 숫자는 표의 병합·계열 구조상 임의 재배분하지 않고 전체 전형 합계만 별도 보존한다." },
  { universityId: "hyupsung", name: "협성대학교", region: "경기", status: "부분검증", priority: 1, source: { type: "university", url: "https://iphak.uhs.ac.kr/ipsi/board/notice/detail.do?bbsNo=32484", academicYear: 2027, confidence: 0.95 }, note: "2027 최종 수시 모집요강과 학생부종합 융합인재Ⅰ·Ⅱ 가이드북을 공식 원문으로 확인했다. 수시 모집단위 카탈로그와 교과성적우수자·미래창의인재·융합인재Ⅰ·Ⅱ·기회균형·사회배려자 핵심 전형을 verified로 편입했다. 전형별 학과별 모집인원 및 음악·디자인·에이블아트·스포츠 실기 세부는 추가 대조한다." },
  { universityId: "kangnam", name: "강남대학교", region: "경기", status: "부분검증", priority: 1, source: { type: "university", url: "https://admission.kangnam.ac.kr/ipsi/yogang.htm?ctg_cd=susi1", academicYear: 2027, confidence: 0.99 }, note: "2027 최종 수시 모집요강을 공식 원문으로 재대조했다. 정원내 959명의 모집단위별 배정을 verified로 편입했다. 논술은 논술80+교과20, 지역균형·농어촌·국가보훈·만학도는 교과100, 학교생활우수자1은 서류100, 학교생활우수자2는 1단계 서류100(3배수) 후 2단계 70+면접30, 실기는 디자인 교과40+실기60·체육 교과20+실기80·음악 실기100으로 확인했다. 정원외 94명은 별도 추천 데이터에서 추가 검증한다." },
  { universityId: "yongin", name: "용인대학교", region: "경기", status: "부분검증", priority: 1, source: adiga("https://www.adiga.kr/ucp/uvt/uni/univDetailSelection.do?menuId=PCUVTINF2000&searchSyr=2027&unvCd=0000156"), note: "2027 수시 정원내 1,014명과 정원외 69명을 공식 자료로 확인했다. 34개 핵심 모집단위와 자율전공 6개 모집단위, AI시스템반도체학과 신설 및 주요 교과전형을 verified로 편입했으며 체육·기회균형의 모집단위별 세부 인원은 추가 대조한다." },
];

export const coverageTargetById = new Map(coverageTargets2027.map((target) => [target.universityId, target]));
