import type { Admission, Department, University } from "./types";
import { admissionSources } from "./sources";

/**
 * 세종대학교 2027학년도 수시모집 공식 모집요강을 기준으로 확인한 데이터.
 */
export const verifiedSejong2027Universities: University[] = [
  { id: "sejong", name: "세종대학교", region: "서울" },
];

const departments = [
  ["law", "법학과", "법·행정"],
  ["business", "경영학부", "경영·경제"],
  ["economics", "경제학과", "경영·경제"],
  ["hotel-tourism", "호텔관광외식경영학부", "호텔·관광"],
  ["hotel-franchise", "호텔외식관광프랜차이즈경영학과", "호텔·관광"],
  ["culinary", "조리서비스경영학과", "호텔·관광"],
  ["korean", "국어국문학과", "인문"],
  ["international", "국제학부", "인문"],
  ["history", "역사학과", "인문"],
  ["education", "교육학과", "교육"],
  ["public-admin", "행정학과", "법·행정"],
  ["media", "미디어커뮤니케이션학과", "미디어"],
  ["math-stat", "수학통계학과", "자연과학"],
  ["physics-astro", "물리천문학과", "자연과학"],
  ["chemistry", "화학과", "자연과학"],
  ["life-system", "생명시스템학부", "생명과학"],
  ["smart-life", "스마트생명산업융합학과", "생명과학"],
  ["ai-electronics", "AI융합전자공학과", "전자·AI"],
  ["semiconductor", "반도체시스템공학과", "반도체"],
  ["cs", "컴퓨터공학과", "컴퓨터·소프트웨어"],
  ["information-security", "정보보호학과", "컴퓨터·소프트웨어"],
  ["quantum-intelligence", "양자지능정보학과", "첨단"],
  ["design-innovation", "디자인이노베이션전공", "예체능"],
  ["animation", "만화애니메이션텍전공", "예체능"],
  ["ai-data", "인공지능데이터사이언스학과", "첨단"],
  ["ai-robot", "AI로봇학과", "첨단"],
  ["intelligent-info", "지능정보융합학과", "첨단"],
  ["contents-software", "콘텐츠소프트웨어학과", "첨단"],
  ["architecture-engineering", "건축공학과", "건축·공학"],
  ["architecture", "건축학과(5년)", "건축·공학"],
  ["civil-environment", "건설환경공학과", "건축·공학"],
  ["environment", "환경융합공학과", "공학"],
  ["energy-resources", "에너지자원공학과", "공학"],
  ["mechanical", "기계공학과", "공학"],
  ["aerospace", "우주항공공학전공", "우주항공"],
  ["drone", "지능형드론융합전공", "첨단"],
  ["nano-materials", "나노신소재공학과", "공학"],
  ["quantum-nuclear", "양자원자력공학과", "공학"],
  ["music", "음악과", "예체능"],
  ["physical-education", "체육학과", "예체능"],
  ["dance", "무용과", "예체능"],
  ["film", "영화예술학과", "예체능"],
] as const;

export const verifiedSejong2027Departments: Department[] = departments.map(([id, name, category]) => ({
  id: `sejong-${id}`,
  universityId: "sejong",
  name,
  category,
}));

const source = admissionSources.sejong2027;
const noCsat = { enabled: false };
const regionalMinimum = { enabled: true, description: "인문·자연계열: 2개 영역 등급 합 6 이내", requiredSubjects: 2, gradeSum: 6 };
const essayMinimum = { enabled: true, description: "인문·자연계열: 2개 영역 등급 합 5 이내", requiredSubjects: 2, gradeSum: 5 };

const make = (
  departmentId: string,
  name: string,
  type: Admission["type"],
  recruitmentCount: number,
  extra: Partial<Admission> = {},
): Admission => ({
  id: `sejong-${departmentId}-${name.replace(/[^가-힣A-Za-z0-9]+/g, "-")}-2027`,
  universityId: "sejong",
  departmentId: `sejong-${departmentId}`,
  academicYear: 2027,
  name,
  type,
  recruitmentCount,
  source,
  isMock: false,
  ...extra,
});

export const verifiedSejong2027Admissions: Admission[] = [
  make("law", "세종인재 전형(면접형)", "학종", 4, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("law", "지역균형", "교과", 4, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("law", "논술우수자", "논술", 4, { studentRecordWeight: 20, csatMinimum: essayMinimum }),

  make("business", "세종인재 전형(면접형)", "학종", 12, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("business", "세종인재 전형(서류형)", "학종", 1, { documentWeight: 100, csatMinimum: noCsat }),
  make("business", "지역균형", "교과", 10, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("business", "논술우수자", "논술", 9, { studentRecordWeight: 20, csatMinimum: essayMinimum }),

  make("economics", "세종인재 전형(면접형)", "학종", 5, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("economics", "지역균형", "교과", 4, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("economics", "논술우수자", "논술", 4, { studentRecordWeight: 20, csatMinimum: essayMinimum }),

  make("korean", "지역균형", "교과", 5, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("korean", "세종인재 전형(면접형)", "학종", 5, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("korean", "논술우수자", "논술", 5, { studentRecordWeight: 20, csatMinimum: essayMinimum }),
  make("international", "지역균형", "교과", 10, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("international", "세종인재 전형(면접형)", "학종", 15, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("history", "세종인재 전형(면접형)", "학종", 6, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("history", "논술우수자", "논술", 6, { studentRecordWeight: 20, csatMinimum: essayMinimum }),
  make("education", "지역균형", "교과", 5, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("education", "세종인재 전형(면접형)", "학종", 5, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("public-admin", "지역균형", "교과", 4, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("public-admin", "세종인재 전형(면접형)", "학종", 4, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("public-admin", "논술우수자", "논술", 3, { studentRecordWeight: 20, csatMinimum: essayMinimum }),
  make("media", "지역균형", "교과", 4, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("media", "세종인재 전형(면접형)", "학종", 4, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("media", "논술우수자", "논술", 4, { studentRecordWeight: 20, csatMinimum: essayMinimum }),

  make("hotel-tourism", "지역균형", "교과", 12, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("hotel-tourism", "세종인재 전형(면접형)", "학종", 14, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("hotel-tourism", "논술우수자", "논술", 9, { studentRecordWeight: 20, csatMinimum: essayMinimum }),

  make("math-stat", "지역균형", "교과", 4, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("math-stat", "세종인재 전형(면접형)", "학종", 5, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("math-stat", "논술우수자", "논술", 7, { studentRecordWeight: 20, csatMinimum: essayMinimum }),
  make("physics-astro", "지역균형", "교과", 6, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("physics-astro", "세종인재 전형(면접형)", "학종", 10, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("physics-astro", "논술우수자", "논술", 7, { studentRecordWeight: 20, csatMinimum: essayMinimum }),
  make("chemistry", "지역균형", "교과", 4, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("chemistry", "세종인재 전형(면접형)", "학종", 5, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("chemistry", "논술우수자", "논술", 4, { studentRecordWeight: 20, csatMinimum: essayMinimum }),
  make("life-system", "지역균형", "교과", 12, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("life-system", "세종인재 전형(면접형)", "학종", 17, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("life-system", "논술우수자", "논술", 12, { studentRecordWeight: 20, csatMinimum: essayMinimum }),
  make("smart-life", "지역균형", "교과", 4, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("smart-life", "세종인재 전형(면접형)", "학종", 4, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("smart-life", "세종인재 전형(서류형)", "학종", 4, { documentWeight: 100, csatMinimum: noCsat }),
  make("smart-life", "논술우수자", "논술", 4, { studentRecordWeight: 20, csatMinimum: essayMinimum }),

  make("ai-electronics", "지역균형", "교과", 9, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("ai-electronics", "세종인재 전형(면접형)", "학종", 11, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("semiconductor", "지역균형", "교과", 5, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("semiconductor", "세종인재 전형(면접형)", "학종", 6, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("semiconductor", "논술우수자", "논술", 6, { studentRecordWeight: 20, csatMinimum: essayMinimum }),
  make("cs", "지역균형", "교과", 10, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("cs", "세종인재 전형(면접형)", "학종", 12, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("cs", "세종인재 전형(서류형)", "학종", 1, { documentWeight: 100, csatMinimum: noCsat }),
  make("cs", "논술우수자", "논술", 10, { studentRecordWeight: 20, csatMinimum: essayMinimum }),
  make("information-security", "지역균형", "교과", 4, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("information-security", "세종인재 전형(면접형)", "학종", 5, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("information-security", "논술우수자", "논술", 4, { studentRecordWeight: 20, csatMinimum: essayMinimum }),
  make("quantum-intelligence", "지역균형", "교과", 8, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("quantum-intelligence", "세종인재 전형(면접형)", "학종", 5, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("quantum-intelligence", "세종인재 전형(서류형)", "학종", 7, { documentWeight: 100, csatMinimum: noCsat }),
  make("quantum-intelligence", "기회균형", "학종", 5, { csatMinimum: noCsat }),
  make("design-innovation", "실기우수자", "기타", 48),
  make("animation", "실기우수자", "기타", 48),

  make("ai-data", "지역균형", "교과", 22, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("ai-data", "세종인재 전형(면접형)", "학종", 10, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("ai-data", "세종인재 전형(서류형)", "학종", 5, { documentWeight: 100, csatMinimum: noCsat }),
  make("ai-data", "기회균형", "학종", 5, { csatMinimum: noCsat }),
  make("ai-data", "사회기여 및 배려자", "학종", 4, { csatMinimum: noCsat }),
  make("ai-data", "논술우수자", "논술", 18),
  make("ai-robot", "지역균형", "교과", 30, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("ai-robot", "세종인재 전형(면접형)", "학종", 14, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("ai-robot", "세종인재 전형(서류형)", "학종", 7, { documentWeight: 100, csatMinimum: noCsat }),
  make("ai-robot", "기회균형", "학종", 7, { csatMinimum: noCsat }),
  make("ai-robot", "사회기여 및 배려자", "학종", 4, { csatMinimum: noCsat }),
  make("ai-robot", "서해5도 학생", "기타", 1),
  make("ai-robot", "논술우수자", "논술", 24),
  make("intelligent-info", "지역균형", "교과", 22, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("intelligent-info", "세종인재 전형(면접형)", "학종", 9, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("intelligent-info", "세종인재 전형(서류형)", "학종", 5, { documentWeight: 100, csatMinimum: noCsat }),
  make("intelligent-info", "기회균형", "학종", 5, { csatMinimum: noCsat }),
  make("intelligent-info", "사회기여 및 배려자", "학종", 4, { csatMinimum: noCsat }),
  make("intelligent-info", "논술우수자", "논술", 17),
  make("contents-software", "지역균형", "교과", 14, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("contents-software", "세종인재 전형(면접형)", "학종", 6, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("contents-software", "세종인재 전형(서류형)", "학종", 5, { documentWeight: 100, csatMinimum: noCsat }),
  make("contents-software", "기회균형", "학종", 4, { csatMinimum: noCsat }),
  make("contents-software", "논술우수자", "논술", 12),

  make("architecture-engineering", "지역균형", "교과", 7, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("architecture-engineering", "세종인재 전형(면접형)", "학종", 8, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("architecture", "지역균형", "교과", 4, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("architecture", "세종인재 전형(면접형)", "학종", 6, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("architecture", "논술우수자", "논술", 5),
  make("civil-environment", "지역균형", "교과", 6, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("civil-environment", "세종인재 전형(면접형)", "학종", 9, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("environment", "지역균형", "교과", 6, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("environment", "세종인재 전형(면접형)", "학종", 8, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("environment", "논술우수자", "논술", 6),
  make("energy-resources", "지역균형", "교과", 7, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("energy-resources", "세종인재 전형(면접형)", "학종", 8, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("mechanical", "지역균형", "교과", 6, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("mechanical", "세종인재 전형(면접형)", "학종", 8, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("mechanical", "논술우수자", "논술", 7),
  make("aerospace", "지역균형", "교과", 4, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("aerospace", "세종인재 전형(면접형)", "학종", 6, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("drone", "지역균형", "교과", 17, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("drone", "세종인재 전형(면접형)", "학종", 7, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("drone", "세종인재 전형(서류형)", "학종", 6, { documentWeight: 100, csatMinimum: noCsat }),
  make("drone", "기회균형", "학종", 4, { csatMinimum: noCsat }),
  make("drone", "논술우수자", "논술", 12),
  make("nano-materials", "지역균형", "교과", 7, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("nano-materials", "세종인재 전형(면접형)", "학종", 9, { documentWeight: 60, interview: true, csatMinimum: noCsat }),
  make("nano-materials", "논술우수자", "논술", 8),
  make("quantum-nuclear", "지역균형", "교과", 6, { studentRecordWeight: 100, csatMinimum: regionalMinimum }),
  make("quantum-nuclear", "세종인재 전형(면접형)", "학종", 7, { documentWeight: 60, interview: true, csatMinimum: noCsat }),

  make("music", "실기우수자", "기타", 38),
  make("physical-education", "예체능 특기자", "기타", 13),
  make("dance", "실기우수자", "기타", 36),
  make("film", "실기우수자", "기타", 45),
];
